feat(tests): add tests

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -6,3 +6,5 @@ dart format --set-exit-if-changed .
 echo "Run Analyzer..."
 flutter analyze || { echo "flutter analyze error"; exit 1; }
 
+echo "Run Tests..."
+flutter test || { echo "flutter test error"; exit 1; }
